### ISSUE TITLE
Make the trace more general

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#267]
Currently `trace_columns` allow `main` and `aux` named segments. We should probably instead allow any named segments. For example,

```
trace_columns:
    segment_0: [a, b, c]
    segment_1: [d, e, f]
    segment_2: [g, h, i]
```

And then second column in `segment_0` can be referenced using `$segment_0[1]`.
